import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";


import { useEffect, useState, useRef, useCallback } from "react";
import { Title } from "src/components/Title";
import { Yomikata } from "src/components/Yomikata";
import { TopMasu } from "src/components/TopMasu";
import { Imi } from "src/components/Imi";
import { Aside } from "src/components/Aside";
import { Bushu } from "src/components/Bushu";
import { Kakusu } from "src/components/Kakusu";
import { Naritachi } from "src/components/Naritachi";
import { Kurikaeshi } from "src/components/Kurikaeshi";
import { Jukugo } from "src/components/Jukugo";
import { Tanbun } from "src/components/Tanbun";

import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const PAGE = [1, 2];
  const INDEX = [1, 2, 3, 4, 5, 6];
  const [grade, setGrade] = useState(4);
  const [Size, setSize] = useState(1.96);
  const [kanji_1, setKanji_1] = useState("漢");
  const [kanji_2, setKanji_2] = useState("字");
  const [isShow_onkun, setIsshow_onkun] = useState(true);
  const [isShow_bushu, setIsshow_bushu] = useState(true);
  const [isShow_naritachi, setIsshow_naritachi] = useState(false);
  const [isShow_imi, setIsshow_imi] = useState(true);
  const [isShow_kurikaeshi, setIsShow_kurikaeshi] = useState(false);
  const [isShow_jukugo, setIsShow_jukugo] = useState(true);
  const [isShow_tanbun, setIsShow_tanbun] = useState(false);
  const [opacity, setOpacity] = useState(0.5);
  const [ichiX, setIchiX] = useState(0);
  const [ichiY, setIchiY] = useState(0);
  const check_flag = [true, false, false, false, false, false];

  //後で学年に合わせた構成を設定する。
  // const changeGrade = (e) => {
  //   se.set.play();
  //   setGrade((grade) => e.target.value);
  // };

  useEffect(() => {
    setIsshow_onkun((isShow_onkun) => {
      if (grade > 2) {
        return true;
      }
      return false;
    });
    setIsshow_bushu((isShow_bushu) => {
      if (grade > 2) {
        return true;
      }
      return false;
    });
  }, [grade]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <Aside></Aside>

        <article className="print_pages">
          <Title g={grade} size={Size}></Title>

          <div style={{ display: "flex", alignContent: "space-between" }}>
            {PAGE.map((item) => {
              return (
                <div style={{ marginInlineEnd: "0.5cm" }}>
                  <section style={{ display: "flex" }}>
          
                    <TopMasu
                      g={grade}
                      size={Size}
                      k_1={kanji_1}
                      k_2={kanji_2}
                      i={item}
                      o={opacity}
                      t={ichiY}
                      r={ichiX}
                    ></TopMasu>
                    <Yomikata g={grade} size={Size} show={isShow_onkun}></Yomikata>

                    {isShow_bushu === true ? <Bushu g={grade} size={Size}></Bushu> : null}

                    <Kakusu g={grade} size={Size}></Kakusu>
                  </section>

                  {isShow_naritachi === true ? <Naritachi g={grade} size={Size}></Naritachi> : null}

                  {isShow_imi === true ? <Imi g={grade} size={Size}></Imi> : null}

                  <Kurikaeshi
                    g={grade}
                    size={Size}
                    k_1={kanji_1}
                    k_2={kanji_2}
                    i={item}
                    o={opacity}
                    t={ichiY}
                    r={ichiX}
                  ></Kurikaeshi>

                  {isShow_kurikaeshi === true ? (
                    <Kurikaeshi
                      size={Size}
                      k_1={kanji_1}
                      k_2={kanji_2}
                      i={item}
                      o={opacity}
                      t={ichiY}
                      r={ichiX}
                    ></Kurikaeshi>
                  ) : null}

                  <Jukugo g={grade} size={Size}></Jukugo>

                  {isShow_jukugo === true ? <Jukugo size={Size}></Jukugo> : null}

                  <Tanbun g={grade} size={Size}></Tanbun>

                  {isShow_tanbun === true ? <Tanbun g={grade} size={Size}></Tanbun> : null}
                </div>
              );
            })}
          </div>
        </article>
      </main>
    </>
  );
}
