import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [PaddingX, setPaddingX] = useState(1.0);
  const [PaddingY, setPaddingY] = useState(1.0);
  const title = {
    g: "三年", //grade
    t: "漢字プリント", //title
    p_1: 120, //page_1
    p_2: 121, //page_2
    n: "名前（　　　　　　　）", //name
  };
  const changePaddingX = (e) => {
    setPaddingX((PaddingX) => e.target.value);
  };
  const changePaddingY = (e) => {
    setPaddingY((PaddingY) => e.target.value);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <aside>
          余白　縦
          <input className="input_S" onChange={changePaddingY} type="number" value={PaddingY} step="0.1"></input>cm
          余白　横横横
          <input className="input_S" onChange={changePaddingX} type="number" value={PaddingX} step="0.1"></input>cm
        </aside>
        <article className="print_pages" style={{ padding: `${PaddingY}cm ${PaddingX}cm` }}>
          <h1>
            {title.g} {title.t} {title.p_1}・{title.p_2} {title.n}
          </h1>
        </article>
      </main>
    </>
  );
}
